DROP SCHEMA IF EXISTS JEJUOPSEOYE;
CREATE SCHEMA JEJUOPSEOYE;
USE JEJUOPSEOYE;

CREATE TABLE `CONTENT` (
	`NO` INT primary key AUTO_INCREMENT	NOT NULL,
	`CONTENTSID`	VARCHAR(100)	NULL,
	`ALLTAG`	VARCHAR(1000)	NULL,
	`TITLE`	VARCHAR(1000)	NULL,
	`ADDRESS`	VARCHAR(1000)	NULL,
	`ROADADDRESS`	VARCHAR(1000)	NULL,
	`TAG`	VARCHAR(1000)	NULL,
	`INTRODUCTION`	VARCHAR(1000)	NULL,
	`LATITUDE`	DOUBLE	NULL,
	`LONGITUDE`	DOUBLE	NULL,
	`POSTCODE`	VARCHAR(1000)	NULL,
	`PHONENO`	VARCHAR(1000)	NULL,
	`LIKEAMOUNT`	INT DEFAULT 0	NULL,
	`CONTENT_VALUE`	VARCHAR(1000)	NULL,
	`CONTENT_LABEL`	VARCHAR(1000)	NULL,
	`IMGPATH`	VARCHAR(1000)	NULL,
	`THUMBNAILPATH`	VARCHAR(1000)	NULL
);

CREATE TABLE `USER` (
	`USER_NO`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`ID`	VARCHAR(100)	NOT NULL,
	`PASSWORD`	VARCHAR(100)	NOT NULL,
	`NICKNAME`	VARCHAR(100)	NOT NULL,
	`EMAIL1`	VARCHAR(1000)	NULL,
    `EMAIL2`	VARCHAR(1000)	NULL,
	`PHONE`	VARCHAR(100)	NULL,
	`KAKAOTOKEN`	VARCHAR(1000)	NULL,
	`STATUS`	VARCHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))	NULL,
	`ROLE`	VARCHAR(10) DEFAULT 'ROLE_USER'	NULL,
	`ENROLL_DATE`	DATETIME  DEFAULT CURRENT_TIMESTAMP	NULL,
	`MODIFY_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP	NULL
);
INSERT INTO `USER` VALUES(0,'admin','$2a$10$8Fdc17qF4RLq5J4NuC5ZJuKv89SGbDmRvJmFO4LKLUQZdUTbAwJVO','관리자','ADMIN','ADMIN.COM','01012341234',DEFAULT,DEFAULT,'ROLE_ADMIN',DEFAULT,DEFAULT);
INSERT INTO `USER` VALUES(0,'test1','$2a$10$WedBM7w2JzCY3lGkhrewxOlNpFnybxqP54XTUic8d7bPofzETsKSm','지나가는행인','visitjeju1','like.com','01012345678',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO `USER` VALUES(0,'test2','$2a$10$WedBM7w2JzCY3lGkhrewxOlNpFnybxqP54XTUic8d7bPofzETsKSm','데이터조사하는지연이','visitjeju2','like.com','01012597546',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO `USER` VALUES(0,'test3','$2a$10$WedBM7w2JzCY3lGkhrewxOlNpFnybxqP54XTUic8d7bPofzETsKSm','제주디자이너윤희','visitjeju3','like.com','01015881588',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO `USER` VALUES(0,'test4','$2a$10$WedBM7w2JzCY3lGkhrewxOlNpFnybxqP54XTUic8d7bPofzETsKSm','월클손흥민','visitjeju4','like.com','01077777777',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);


CREATE TABLE `REPLY` (
	`REPLY_NO`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`BOARD_NO`	INT	NOT NULL,
	`USER_NO`	INT	NOT NULL,
	`CONTENT`	VARCHAR(1000)	NULL,
	`STATUS`	VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))	NULL,
	`CREATE_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP	NULL,
	`MODIFY_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP	NULL
);

CREATE TABLE `BOARD` (
	`BOARD_NO`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`USER_NO`	INT	NOT NULL,
	`TITLE`	VARCHAR(100)	NULL,
	`CONTENT`	VARCHAR(2000)	NULL,
	`ORIGINAL_FILENAME`	VARCHAR(1000)	NULL,
	`RENAMED_FILENAME`	VARCHAR(1000)	NULL,
	`READCOUNT`	INT DEFAULT 0	NULL,
	`STATUS`	VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))	NULL,
	`CREATE_DATE`	DATETIME  DEFAULT CURRENT_TIMESTAMP	NULL,
	`MODIFY_DATE`	DATETIME  DEFAULT CURRENT_TIMESTAMP	NULL,
    `TYPE` VARCHAR(100)
);

insert into `board` values(0,1,"개인정보처리방침 개정 시행안내","제주관광정보 홈페이지를 이용해 주시는 고객 여러분께 감사의 말씀드리며, 새로운 개인정보취급방침 시행에 관한 안내 말씀 드립니다.\r\n
새롭게 바뀌는 개인정보취급방침의 변경사항을 확인하시어, 서비스 이용에 참고하시기 바랍니다.\r\n\r\n
- 변경사항\r\n
1. 개인정보보호책임자 변경\r\n
2. 개인정보처리 위탁사항 현행화\r\n\r\n
변경된 개인정보취급방침은 2017년 2월 24일자로 효력이 발생합니다.\r\n 관련하여 궁금하신 점이나 소중한 의견은 언제든지 개인정보보호 전담자(064-740-6954)에게 알려주시면 안내해 드리겠습니다.감사합니다.",
default,default,default,default,'2022-12-29 17:00:00','2022-12-29 17:00:00',"notice");
insert into `board` values(0,1,"사이트 이용사항","1. 논란을 조장하면 안됩니다. \r\n
2. 사이트를 이용하는 모두에게 친절하게 대해주세요. \r\n
3. 불법사이트의 공유를 하면 안됩니다.",default,default,default,default,'2022-12-30 09:00:00','2022-12-30 09:00:00',"notice");
insert into `board` values(0,1,"처음 이용하는 고객님들을 위한","단지 좋은 정보들 가져가시면 됩니다.",default,default,default,default,default,default,"notice");
insert into `board` values(0,1,"이벤트 당첨자 공지","이유광 고객님\r\n김지연 고객님\r\n박윤희 고객님\r\n박태성 고객님\r\n이상진 고객님\r\n이윤호 고객님\r\n\r\n당첨을 축하드립니다!!!",default,default,default,default,default,default,"notice");
insert into `board` values(0,1,"마지막으로 팀원분들에게","다들 정말 고생 많으셨습니다!!!!\r\n파이널 프로젝트도 다들 화이팅입니다!!!!",default,default,default,default,default,default,"notice");

insert into `board` values(0,1,"자유게시판 예시글","적고 싶으신 내용을 적으시면 됩니다.\r\n하지만 논란의 소지가 있는 말은 안됩니다.",default,default,default,default,default,default,"free");
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(2,'제주협재해수욕장','정말 아름다운 바다를 볼 수 있었어요!','제주협재해수욕장.jpg','20221230_143247782.jpg',100,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(3,'한라산국립공원','푸르른 산을 마음껏 보고 왔습니다.','한라산국립공원1.jpg','20221230_143306972.jpg',50,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(4,'오설록티뮤지엄','유익한 시간이었습니다.','오설록티뮤지엄.jpg','20221230_143320752.jpg',10,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(4,'천지연폭포','떨어지는 폭포가 정말 시원했습니다.','천지연폭포.jpg','20221230_143334428.jpg',77,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(2,'쇠소깍','아름다운 경치를 감상했습니다.','쇠소깍.jpg','20221230_143349517.jpg',8,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(2,'한라산국립공원','겨울의 한라산을 눈에 담을 수 있어 좋았어요!','한라산국립공원2.jpg','20221230_143405452.jpg',41,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(3,'사려니숲길','피톤치드 향을 맘껏 느꼈습니다!','사려니숲길.jpg','20221230_143421545.jpg',63,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(2,'카멜리아힐','꽃들이 정말 이뻐요. 사진 정말 많이 찍었어요~','카멜리아힐.jpg','20221230_143434621.jpg',34,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(2,'월정리해변','바다가 정말 이뻐요. 사진 정말 많이 찍었어요~','월정리해변.jpg','20221230_143445718.jpg',83,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(4,'비자림','힘든 시기였는데 힐링하고 갑니다!','비자림.jpg','20221230_143455944.jpg',17,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(3,'새별오름','자유로이 걸으며 힐링하고 갑니다!','새별오름.jpg','20221230_143508428.jpg',24,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(3,'세화해변','좋은 사진 건졌어요.','세화해변.jpg','20221230_143517595.jpg',74,'review');
INSERT INTO `BOARD`(`USER_NO`,`TITLE`,`CONTENT`,`ORIGINAL_FILENAME`,`RENAMED_FILENAME`,`READCOUNT`,`TYPE`) VALUES(3,'깅녕해수욕장','탁트인 바다를 보이 마음이 편해요.','깅녕해수욕장.jpg','20221230_143525880.jpg',27,'review');

CREATE TABLE `WANTLIST` (
	`USER_NO`	INT	NOT NULL,
	`CONTENT_NO`	INT	NULL
);



CREATE TABLE `CONTENT_REPLY` (
	`CONTENT_REPLY_NO`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CONTENT_NO`	INT	NOT NULL,
	`USER_NO`	INT	NOT NULL,
	`CONTENT`	VARCHAR(1000)	NULL,
	`STATUS`	VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))	NULL,
	`CREATE_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP	NULL,
	`MODIFY_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP	NULL
);

CREATE TABLE `RESERVATION_LIST` (
	`USER_NO`	INT	NOT NULL,
	`CONTENT_NO`	INT	NULL
);

ALTER TABLE `REPLY` ADD CONSTRAINT `BOARD_TO_REPLY_1` FOREIGN KEY (
	`BOARD_NO`
)
REFERENCES `BOARD` (
	`BOARD_NO`
);

ALTER TABLE `WANTLIST` ADD CONSTRAINT `FK_USER_TO_WANTLIST_1` FOREIGN KEY (
	`USER_NO`
)
REFERENCES `USER` (
	`USER_NO`
);

ALTER TABLE `WANTLIST` ADD CONSTRAINT `FK_CONTENT_TO_WANTLIST_1` FOREIGN KEY (
	`CONTENT_NO`
)
REFERENCES `CONTENT` (
	`NO`
);


ALTER TABLE `CONTENT_REPLY` ADD CONSTRAINT `FK_CONTENT_TO_CONTENT_REPLY_1` FOREIGN KEY (
	`CONTENT_NO`
)
REFERENCES `CONTENT` (
	`NO`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `FK_USER_TO_RESERVATION_LIST_1` FOREIGN KEY (
	`USER_NO`
)
REFERENCES `USER` (
	`USER_NO`
);

ALTER TABLE `RESERVATION_LIST` ADD CONSTRAINT `FK_CONTENT_TO_RESERVATION_LIST_1` FOREIGN KEY (
	`CONTENT_NO`
)
REFERENCES `CONTENT` (
	`NO`
);





SELECT*FROM `USER`;
SELECT*FROM `BOARD`;
SELECT*FROM `REPLY`;
SELECT*FROM `CONTENT`;
SELECT*FROM `CONTENT_REPLY`;
SELECT*FROM `RESERVATION_LIST`;



----------------------------------- DDL 끝-------------------------------------------

-- USER DML

-- 유저 조회
-- SELECT * FROM `USER` WHERE ID=? AND STATUS='Y'

-- 유저 추가
/*
INSERT INTO `USER`(
`USER_NO`,`ID`,`PASSWORD`,`NICKNAME`,
`EMAIL`,`PHONE`,`KAKAOTOKEN`,`STATUS`,
`ROLE`,`ENROLL_DATE`,`MODIFY_DATE`)
 VALUES(0,?,?,?,?,?,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT)
*/
-- 카카오 유저 추가
-- INSERT INTO `USER` VALUES(0,?,?,?,?,?,?,DEFAULT,DEFAULT,DEFAULT)

-- 유저 수정               
-- UPDATE `USER` SET `NICKNAME`=?,`EMAIL`=?,`PHONE`=?, WHERE `USER_NO`=?

-- 유저 패스워드 변경
-- UPDATE `USER` SET `PASSWORD`=? WHERE `USER_NO`=?

-- 유저 삭제
-- UPDATE `USER` SET STATUS='N' WHERE `USER_NO`=?



-- BOARD DML


-- 총 게시글 갯수
-- SELECT COUNT(*) FROM `BOARD` WHERE STATUS='Y'

-- 조회수 증가
-- UPDATE `BOARD` SET READCOUNT=? WHERE NO=?

-- 게시글 작성
-- INSERT INTO `BOARD` VALUES(0,?,?,?,?,?,DEFAULT,DEFAULT,DEFAULT,DEFAULT,?)

-- 게시글 수정
/*
UPDATE `BOARD` 
SET TITLE=?,CONTENT=?,ORIGINAL_FILENAME=?,
RENAMED_FILENAME=?,MODIFY_DATE=CURRENT_TIMESTAMP 
WHERE `BOARD_NO`=?
*/

-- 게시글 삭제
-- UPDATE `BOARD` SET STATUS='N' WHERE NO=?

-- 상세 조회
/*
SELECT  B._NO, B.TITLE, U.NICKNAME, B.READCOUNT, B.ORIGINAL_FILENAME, B.RENAMED_FILENAME, B.CONTENT, B.CREATE_DATE, B.MODIFY_DATE
FROM `BOARD` B
JOIN `USER` U ON(B.USER_NO = U.USER_NO)
WHERE B.STATUS = 'Y' AND B.NO=?
*/

-- 목록 조회(페이징) 쿼리
/*
SELECT  B.NO, B.TITLE, M.ID, B.CREATE_DATE, B.ORIGINAL_FILENAME, B.READCOUNT, B.STATUS
FROM `BOARD` B JOIN `USER` U ON(B.USER_NO = U.USER_NO) 
WHERE B.STATUS = 'Y' 
ORDER BY B.NO DESC LIMIT 10 OFFSET 0;
*/

-- 리플 작성
-- INSERT INTO `REPLY` VALUES(0, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT)

-- 리플 삭제
-- UPDATE `REPLY` SET STATUS='N' WHERE NO=?

-- 한 게시판에 해당하는 댓글 리스트 조회용 쿼리문
/*
SELECT R.REPLY_NO, R.BOARD_NO, R.CONTENT, M.ID, R.CREATE_DATE, R.MODIFY_DATE
FROM `REPLY` R
JOIN USER U ON(R.USER_NO = U.USER_NO)
WHERE R.STATUS='Y' AND BOARD_NO= ? 
ORDER BY R.REPLY_NO DESC;
*/

-- 검색 + 쿼리문
/*
SELECT  B.BOARD_NO, B.TITLE, U.NICKNAME, B.CREATE_DATE, B.ORIGINAL_FILENAME, B.READCOUNT, B.STATUS
FROM `BOARD` B JOIN USER U ON(B.USER_NO = U.USER_NO) 
WHERE 1 = 1 
AND B.STATUS = 'Y'
AND U.ID LIKE '%admin%' 
AND B.TITLE LIKE '%구매%' 
AND B.CONTENT LIKE '%아이폰%' 
ORDER BY B.BOARD_NO DESC LIMIT ? OFFSET ?;
*/


-- CONTENT DML

-- 데이터 삽입
/*
INSERT INTO `CONTENT`(
`CONTENTSID`,`ALLTAG`,`TITLE`,
`ADDRESS`,`ROADADDRESS`,`TAG`,
`INTRODUCTION`,`LATITUDE`,`LONGITUDE`,
`POSTCODE`,`PHONENO`,`LIKEAMOUNT`,
`CONTENT_VALUE`,`CONTENT_LABEL`,`IMGPATH`,`THUMBNAILPATH`) 
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
*/
/*
INSERT INTO `CONTENT`(
`CONTENTSID`,`ALLTAG`,`TITLE`,
`ADDRESS`,`ROADADDRESS`,`TAG`,
`INTRODUCTION`,`LATITUDE`,`LONGITUDE`,
`POSTCODE`,`PHONENO`,`LIKEAMOUNT`,
`CONTENT_VALUE`,`CONTENT_LABEL`,`IMGPATH`,`THUMBNAILPATH`) 
VALUES("CNTS_200000000013168","축제, 문화관광","세계자동차&피아노박물관 4TH 봄날의 향연 뮤지엄콘서트","제주특별자치도 서귀포시 안덕면 상창리 2065-4",
"제주특별자치도 서귀포시 안덕면 중산간서로 1610","축제,문화관광,행사,박물관,실내관광지,봄","세계자동차&피아노박물관 로비 따뜻한 봄날에 즐기는 국내 유일 오리지널 하프시코드와 함께하는 렉처 콘서트 ",
33.2831948,126.349772,NULL,"064-792-3000",DEFAULT,"C5","축제/행사","HTTPS://API.CDN.VISITJEJU.NET/PHOTOMNG/IMGPATH/202203/23/8AEC48A8-4857-4871-A3C5-12A79611B9F6.JPG",
"HTTPS://API.CDN.VISITJEJU.NET/PHOTOMNG/THUMBNAILPATH/202203/23/32C71E40-7651-4C4A-83DF-AD6218634DC1.JPG");
*/

